CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    role       VARCHAR(255)                            NOT NULL,
    manager_id BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_MANAGER FOREIGN KEY (manager_id) REFERENCES users (id);


-- Inserting an admin user
INSERT INTO users (username, password, first_name, last_name, email, role)
VALUES ('admin_user', 'password123', 'Admin', 'User', 'admin@example.com', 'ADMIN');

-- Inserting a regular user with a manager (manager_id refers to the admin user above)
INSERT INTO users (username, password, first_name, last_name, email, role, manager_id)
VALUES ('jdoe', 'password456', 'John', 'Doe', 'johndoe@example.com', 'USER', 1);

-- Inserting another regular user without a manager
INSERT INTO users (username, password, first_name, last_name, email, role)
VALUES ('asmith', 'password789', 'Alice', 'Smith', 'alicesmith@example.com', 'USER');


CREATE TABLE tags
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_tags PRIMARY KEY (id)
);


CREATE TABLE tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    due_date    TIMESTAMP WITHOUT TIME ZONE,
    completed   BOOLEAN                                 NOT NULL,
    assigned_to VARCHAR(255),
    created_by  VARCHAR(255),
    tokens      INTEGER                                 NOT NULL,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);


CREATE TABLE tasks_tags
(
    task_id BIGINT NOT NULL,
    tag_id  BIGINT NOT NULL,
    CONSTRAINT pk_tasks_tags PRIMARY KEY (task_id, tag_id)
);

INSERT INTO tags (name) VALUES
                            ('Bug'),
                            ('Feature Request'),
                            ('Enhancement'),
                            ('Urgent'),
                            ('UI/UX'),
                            ('Backend'),
                            ('Frontend'),
                            ('Database'),
                            ('Performance'),
                            ('Security'),
                            ('High Priority'),
                            ('Low Priority'),
                            ('Testing'),
                            ('Documentation'),
                            ('Research');
