CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    role       VARCHAR(255)                            NOT NULL,
    manager_id BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_MANAGER FOREIGN KEY (manager_id) REFERENCES users (id);


-- Inserting an admin user
INSERT INTO users (username, password, first_name, last_name, email, role)
VALUES ('admin_user', 'password123', 'Admin', 'User', 'admin@example.com', 'ADMIN');

-- Inserting a regular user with a manager (manager_id refers to the admin user above)
INSERT INTO users (username, password, first_name, last_name, email, role, manager_id)
VALUES ('jdoe', 'password456', 'John', 'Doe', 'johndoe@example.com', 'USER', 1);

-- Inserting another regular user without a manager
INSERT INTO users (username, password, first_name, last_name, email, role)
VALUES ('asmith', 'password789', 'Alice', 'Smith', 'alicesmith@example.com', 'USER');
